### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Sukkiiiiii12** [forcedotcom/salesforcedx-vscode-slds#100]
- Issue Type: `Bug`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.4.8`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
"The XML language server crashed 5 times in the last 10 minutes. The server will not be restarted."
Extenton ID: redhat.vscode-xml

**Comment by billyma** [comment]
Thanks for filing this issue. However, based on the information provided, `Extension ID: redhat.vscode-xml`, the issue belongs to [redhat-developer/vscode-xml](https://github.com/redhat-developer/vscode-xml/issues). 

Hence, we are closing this issue for now. Thanks.
