### ISSUE TITLE
Validation Mismatch

### ISSUE THREAD

**Issue by shunkosa** [forcedotcom/salesforcedx-vscode-slds#19]
### Summary

Hello team, thank you for this useful extension. I found some validation mismatch when I used HTML tags in SLDS website directly.

### Steps To Reproduce:

1.  Copy code of 'Base' section tag in [Checkbox Button Group](https://www.lightningdesignsystem.com/components/checkbox-button-group/) and then paste it to component html.

### Expected result

No error shows.

### Actual result

Deprecated, or invalid, utility class found.

### Additional information
Same as [record home](https://www.lightningdesignsystem.com/components/page-headers/).

<img width="994" alt="example1" src="https://user-images.githubusercontent.com/1404346/77718463-5bd56000-7026-11ea-888d-2037ce42e81f.png">
<img width="975" alt="example2" src="https://user-images.githubusercontent.com/1404346/77718472-5ed05080-7026-11ea-95df-6152fd83e298.png">

**VS Code Version**: 1.43.2

**SFDX CLI Version**: 7.50.0

**OS and version**: Mac OS 10.15.3

**Comment by billyma** [comment]
Issue is fixed with #21.
