### ISSUE TITLE
Don't auto show "Request textDocument/codeAction failed" message 

### ISSUE THREAD

**Issue by xyc** [forcedotcom/salesforcedx-vscode-slds#25]
### Summary

Don't auto show "Request textDocument/codeAction failed" message in LWC components that have errors.
<img width="653" alt="Screen Shot 2020-06-10 at 5 08 37 PM" src="https://user-images.githubusercontent.com/679275/84330932-99ce2480-ab3d-11ea-925b-6da6f127103f.png">

### Steps To Reproduce:

1.  type `@track property;` (don't auto complete) in an LWC component
2. There should be an issue in problem panel "Supported decorators (api, wire, track) should be imported from "lwc".
3. The output panel opens and SLDS extension shows "Request textDocument/codeAction failed" message in output panel. This is not an ideal experience since the message is not helpful for the user and the LWC language features already handle the error message / quick fix.

### Expected result

Output panel should not open

### Actual result

Output panel opens

**Comment by kirupa** [comment]
Thanks for letting us know, xyc. I'll follow-up with the team and look into getting it addressed soon.

**Comment by xyc** [comment]
Looks like this is a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/2074 - Closing it out
