### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Yasir-Sheriff** [forcedotcom/salesforcedx-vscode-slds#28]
- Issue Type: `Performance`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.1.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\yasir.sheriff\salesforce.salesforce-vscode-slds-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ambreeen** [comment]
Hi @Yasir-Sheriff. Thanks for bringing up this issue. Can you attach your `cpuprofile.txt` file here?
