### ISSUE TITLE
Incorrectly replacing with design token

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/salesforcedx-vscode-slds#33]
### Summary

When replacing some hardcoded value with a design token, you still need to wrap the design token into a var, replace with the --lwc- prefix, and add the default value in case the design token is not found

### Steps To Reproduce:

1.  Create a css entry
1.  Add some hardcoded value to a property, for example `margin: 16px`
1.  Replace with the design token

### Expected result

Correctly wrapping with the var, the prefix and the default value

### Actual result

Just erasing the value, and putting the design token

### Additional information

![errorslds](https://user-images.githubusercontent.com/10410852/88532333-b8608000-d004-11ea-8444-678af4e86e93.gif)

**VS Code Version**: 1.47.2

**SFDX CLI Version**:

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ salesforce-alm 49.3.0 (core)
├─ custom-metadata 1.0.7 (core)
├─ salesforcedx-templates 48.32.0 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.66.2 (core)
sfdx-wry-plugin 0.0.11

**OS and version**: WSL 2 Running in Windows 10

**Comment by ambreeen** [comment]
Thanks for reporting. Fixed in the latest release.
