### ISSUE TITLE
Update Token not working 

### ISSUE THREAD

**Issue by vishnusundar2607** [forcedotcom/salesforcedx-vscode-slds#44]
### Summary

SLDS validator update token not working as expected

### Steps To Reproduce:
1.  type below in LWC .html file 
       <div class="slds-p-horizontal_small">
       </div>
2. SLDS validator will show Updated Design Token Available like "slds-var-p-horizontal_small".
3.right Click on message and click update token 

### Expected result

Updated token should be updated in LWC .HTML file

### Actual result

Token not updated in .HTML file

**VS Code Version**: 1.48.1

**SFDX CLI Version**: 7.70.1

**OS and version**: Windows 10 latest

**Comment by ambreeen** [comment]
Thanks for reporting. A fix has been made for this and will be deployed soon.

**Comment by ambreeen** [comment]
Latest release addresses this issue. Thanks.
