### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jdarangor** [forcedotcom/salesforcedx-vscode-slds#46]
- Issue Type: `Performance`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\jdara\salesforce.salesforce-vscode-slds-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jdarangor** [comment]
Automatic response vscode
[salesforce.salesforce-vscode-slds-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode-slds/files/5177488/salesforce.salesforce-vscode-slds-unresponsive.cpuprofile.txt)

**Comment by ambreeen** [comment]
Thanks for reporting. We are investigating this issue.

**Comment by billyma** [comment]
This issue should be addressed with the attached PR. Closing the issue for now.
