### ISSUE TITLE
slds-current-color should be allowed

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode-slds#48]
### Summary

`slds-current-color` is being flagged with the error `Deprecated, or invalid, utility class: "slds-current-color"`

### Steps To Reproduce:

```html
<a href="#">
  <lightning-icon class="slds-current-color" icon-name="utility:chevronright"></lightning-icon>Link Text
</a>
```

### Expected result

Following public SLDS docs works
https://www.lightningdesignsystem.com/components/icons/#Current-Color

### Actual result

error message
### Additional information

_Feel free to attach a screenshot_.
![Screen Shot 2020-09-10 at 1 53 12 PM](https://user-images.githubusercontent.com/4261788/92785378-faebdb00-f36c-11ea-817e-2ab811a8e666.png)

**VS Code Version**:
1.48.2
**SFDX CLI Version**:
sfdx-cli/7.68.6 darwin-x64 node-v12.14.0

**OS and version**:
osx catalina 10.15.6 (19G2021)

**Comment by ambreeen** [comment]
Hi @mshanemc, thanks for reporting. This appears to be a bug that we should have a fix for soon.

**Comment by ambreeen** [comment]
@mshanemc  This issue should be fixed now with the latest release. Thanks!
