### ISSUE TITLE
slds-listbox__item should be allowed

### ISSUE THREAD

**Issue by ctchipps** [forcedotcom/salesforcedx-vscode-slds#49]
### Summary

`slds-listbox__item` is being flagged with the error `Deprecated, or invalid, utility class: "slds-listbox__item"`

### Steps To Reproduce:

```
<li role="presentation" class="slds-listbox__item"></li>
```

### Expected result

Following public SLDS docs works
https://www.lightningdesignsystem.com/components/combobox

### Actual result

error message

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/36672126/93116112-d5bbdd00-f68a-11ea-8f4d-c833cb4dc064.png)

**VS Code Version**:
1.49.0

**SFDX CLI Version**:
sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1

**OS and version**:
Microsoft Windows 10 Enterprise
10.0.19041 Build 19041

**Comment by ambreeen** [comment]
Thank you for reporting @ctchipps. We are working on a fix for this and will have an update by the next release.

**Comment by ambreeen** [comment]
@ctchipps This issue should be fixed now with the latest release. Thanks!
