### ISSUE TITLE
Plugin should be activated only in salesforce project

### ISSUE THREAD

**Issue by shunkosa** [forcedotcom/salesforcedx-vscode-slds#51]
**Is your feature request related to a problem? Please describe.**
SLDS validator is activated in non sfdx projects like general html/css directory, react, vue, angular, and so on. I'm bothered by disabling it manually.

![image](https://user-images.githubusercontent.com/1404346/93425469-069f4a80-f8f5-11ea-9a25-a6b0ac57295e.png)

**Describe the solution you'd like**
This plugin should only be activated in the directly which has `sfdx-project.json`.

**Describe alternatives you've considered**
Disable manually for non salesforce project.

**Additional context**

**Comment by ambreeen** [comment]
Thanks for bringing this to our attention. We have updated the experience for this and it will be available by the next release.

**Comment by ambreeen** [comment]
@shunkosa This issue should be fixed now with the latest release. Thanks!
