### ISSUE TITLE
slds-checkbox_on marked incorrectly as "Deprecated or invalid utility class"

### ISSUE THREAD

**Issue by sunqing99** [forcedotcom/salesforcedx-vscode-slds#56]
### Summary

In VS Code, the "slds-checkbox_on" class is marked as _Deprecated, or invalid, utility class: "slds-checkbox_on"_ and suggested quick fix is to remove the class. However, if I remove the class, the widget will not show correctly (the "on" label will show even when the checkbox is toggled false which is incorrect)

### Steps To Reproduce:

1.  See [this file](https://git.soma.salesforce.com/service-cloud-perf/lwc-vpod-dashboard/blob/af37cd6cb94c7df4ab36e3e514b224a704751cfb/src/client/modules/my/labItem/labItem.html#L98) in VS Code

### Expected result

If the slds-checkbox_on class is valid, there should be no warning; if it is invalid or outdated, there should be a correct suggested quick fix

### Actual result

The class is marked as Deprecated, or invalid, utility class: "slds-checkbox_on"

### Additional information

![Screen Shot 2020-09-23 at 5 34 04 PM](https://user-images.githubusercontent.com/8459231/94088037-33a39f80-fdc4-11ea-8f63-d4af38ab7350.png)

**VS Code Version**: 1.49.1

**SFDX CLI Version**: 7.73.2

**OS and version**: macOS Catalina

**Comment by sunqing99** [comment]
The list of auto-complete suggestions does not include slds-checkbox_on, and also there are multiple entries of slds-checkbox_faux and slds-checkbox_off

**Comment by ambreeen** [comment]
@sunqing99 This issue should be fixed now with the latest release. Thanks!
