### ISSUE TITLE
LOVE the Validator!  Why Does It Sometimes Not Run?

### ISSUE THREAD

**Issue by GH4Arlene** [forcedotcom/salesforcedx-vscode-slds#61]
### Summary

Sometimes, apparently randomly, the SLDS validator stops finding issues.  What controls when it is off and when it is on?  I LOVE it, and really miss it when it's not working.

### Steps To Reproduce:

I wish I knew what causes it.  That's my question

### Expected result

Would expect "slds-m-around_medium"  to have a red squiggly line under it, because it is missing "var-"

### Actual result

No slds errors or warnings are detected.

### Additional information

This has happened over the course of several versions of VCCode and the CLI, so is probably not version specific.  The problem comes and goes.  It will work for several days or weeks and then not work for several days or weeks.

**VS Code Version**:  1.50.1

**SFDX CLI Version**:  50.1.1

**OS and version**:  Windows 10 Enterprise  10.0.17763 Build 17763

**Comment by billyma** [comment]
@GH4Arlene - Can you provide a screenshot, or video, when the issue happen? It would help us to identify the cause? Thanks.

**Comment by GH4Arlene** [comment]
Here is a screen shot, but I don’t think it will give you any information.  It’s just a screen shot of no red underlines.  There should be red underline on line 23, as the “var-“ is missing.  Please let me know if there is anything else I can do to help.  I’m happy to look anything up or change any settings to troubleshoot.

[cid:image001.png@01D6A62D.63F15DB0]

Arlene Stebbins
Hearth Expert
Web Developer
Cell: 253-370-2258
stebbinsa@hearthnhome.com

**Comment by billyma** [comment]
I am able to reproduce the issue. I captured the output log. 
<img width="1018" alt="Screen Shot 2020-10-19 at 4 05 07 PM" src="https://user-images.githubusercontent.com/1031332/96521424-18427d80-1226-11eb-9690-8dc79130ff92.png">

Can you confirm if you are seeing the same output in your log? Thanks.

**Comment by GH4Arlene** [comment]
This is what I see:
```
Starting SLDS ... registering commands ... registering providers
Storing LSP server log in 'c:\Users\(user)\AppData\Roaming\Code\User\workspaceStorage\992ddc1cbf5dff1fbec19653d903f5ca\salesforce.salesforce-vscode-slds/slds-extension.log'
SLDS Started
```

The error log listed in the Output has a ton of errors.  Here is the first part of the file...it goes on for several hundred similar lines.  I've removed my system and user names for security reasons:


 ```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.3.RELEASE)

Oct 19, 2020 1:42:53 PM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting ServerLauncher on (system name) with PID 1736 (C:\Users\(user)\.vscode\extensions\salesforce.salesforce-vscode-slds-1.3.0\lsp-0.0.6-executable.jar started by (user) in c:\Users\(user)\vworkspace\myhhtqa)
Oct 19, 2020 1:42:53 PM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Oct 19, 2020 1:43:01 PM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started ServerLauncher in 9.547 seconds (JVM running for 12.595)
Oct 19, 2020 1:43:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1
Oct 19, 2020 1:48:17 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
Oct 19, 2020 1:48:18 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
Oct 19, 2020 1:56:42 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation


```

**Comment by sravani-gadaputi** [comment]
Am also facing the same issue.
Can you please provide the Solution..

**Comment by billyma** [comment]
We are working on this. Will post an update later this week.

**Comment by billyma** [comment]
Creates PR as an attempt to address the issues. Please let us know how it goes.

**Comment by ambreeen** [comment]
The latest release addresses these issues. If you still see any issues, please let us know and reopen this issue or create a new one. Thanks!
