### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by raghudeep77** [forcedotcom/salesforcedx-vscode-slds#68]
- Issue Type: `Bug`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ambreeen** [comment]
@raghudeep77 Would you be able to provide us with more information on what the issue is? A screenshot or video perhaps?
