### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by viniN001** [forcedotcom/salesforcedx-vscode-slds#71]
- Issue Type: `Bug`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kirupa** [comment]
Hi @viniN001 - can you provide more details? It's not clear what the problem is based on what you've commented 😄

**Comment by ambreeen** [comment]
Closing this issue since there has been no followup.
