### ISSUE TITLE
SLDS Validator application to Lightning Web Component CSS?

### ISSUE THREAD

**Issue by shanayze** [forcedotcom/salesforcedx-vscode-slds#83]
<We are using the SLDS Validator for VS plugin found below. It says it works for Aura and Lightning. We have several Lightning Web Components that have our own styling and we'd like to convert all the styling to the Lightning Design System. However when we open a CSS, we do not see any highlighting or indicators that the plugin is working. See screenshot attached. Can someone help with this? Does it work on LWC? Or just on custom components?

https://www.lightningdesignsystem.com/tools/validator/

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.56.2

**SFDX CLI Version**:
sfdx-cli/7.81.0 win32-x64 node-v12.9.0

**OS and version**:
Windows 10 Pro

<img width="1609" alt="No Validation" src="https://user-images.githubusercontent.com/20405543/118892737-32286980-b8b6-11eb-92dd-616a513add49.png">

**Comment by gogowater** [comment]
I have the same issue and this is what I found in the log.

May 28, 2021 11:17:54 AM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting ServerLauncher on [machine name] with PID 43828 (C:\Users\kevin\.vscode\extensions\salesforce.salesforce-vscode-slds-1.4.4\lsp-0.0.9-executable.jar started by kevin in c:\Projects\Salesforce\salesforce-connector)
May 28, 2021 11:17:54 AM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
May 28, 2021 11:17:56 AM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started ServerLauncher in 3.502 seconds (JVM running for 4.064)
May 28, 2021 11:18:04 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1
May 28, 2021 11:18:04 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
May 28, 2021 11:20:10 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
May 28, 2021 11:20:11 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 4
May 28, 2021 11:20:18 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 5
May 28, 2021 11:20:18 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 6
May 28, 2021 11:20:21 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 7
May 28, 2021 11:20:22 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8
May 28, 2021 11:20:39 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 9
May 28, 2021 11:22:58 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification

**Comment by billyma** [comment]
Thanks for reporting the issue. We have identified the fix. Until the change is released to production, you can leverage this temporary workaround:

Within VSCode, enable `SLDS: Do not scope SLDS Validator to SFDX project files` to the necessary workspace  or project.

**Comment by gogowater** [comment]
Hi @billyma ,

I tested with your recommendation for the workaround and I am getting the error.  Any idea how I could resolve this?

settings.json
{
    "salesforcedx-vscode-slds.enhancements.autoSuggest": true,
    "salesforcedx-vscode-slds.file.scopeWithInSFDX": false,
    "salesforcedx-vscode-apex.java.home": "C:\\program files\\AdoptOpenJDK\\jdk-8.0.222.10-hotspot",
    "salesforcedx-vscode-slds.enabled": true
}

slds-extension.log:
Jun 01, 2021 9:28:20 AM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting ServerLauncher on [machine name] with PID 23760 (C:\Users\kevin\.vscode\extensions\salesforce.salesforce-vscode-slds-1.4.4\lsp-0.0.9-executable.jar started by kevin in c:\Projects\Salesforce\salesforce-connector)
Jun 01, 2021 9:28:20 AM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Jun 01, 2021 9:28:22 AM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started ServerLauncher in 3.294 seconds (JVM running for 4.039)
Jun 01, 2021 9:28:28 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///c%3A/Projects/Salesforce/salesforce-connector/force-app/main/default/aura/setupAssistant/setupAssistant.css",
      "languageId": "css",
      "version": 1,
      "text": "@-webkit-keyframes strike-section-completion {\r\n    0% {\r\n        transform: scale(0) rotate(10deg);\r\n        opacity: 0;\r\n    }\r\n    40% {\r\n        opacity: 1;\r\n    }\r\n    80% {\r\n        transform: scale(1.2);\r\n    }\r\n    100% {\r\n        transform: scale(1);\r\n    }\r\n}\r\n\r\n@keyframes strike-section-completion {\r\n    0% {\r\n        transform: scale(0);\r\n        opacity: 0;\r\n    }\r\n    40% {\r\n        opacity: 1;\r\n    }\r\n    80% {\r\n        transform: scale(1.2);\r\n    }\r\n    100% {\r\n        transform: scale(1);\r\n    }\r\n}\r\n\r\n.THIS.slds-scope .strike-logo-container img {\r\n    max-width: 400px;\r\n    width: auto;\r\n    max-height: 200px;\r\n    height: auto;\r\n}\r\n\r\n.THIS.slds-scope .strike-notify {\r\n    max-width: 100%;\r\n    min-width: 0;\r\n    width: 100%;\r\n    margin: 0;\r\n}\r\n\r\n.THIS.slds-scope .slds-picklist .slds-dropdown {\r\n   width: 100%;\r\n}\r\n\r\n.THIS.slds-scope .strike-icon-text-success {\r\n    color: t(colorTextSuccessInverse);\r\n    fill: t(colorTextSuccessInverse);\r\n}\r\n\r\n.THIS.slds-scope .strike-icon-text-success .slds-icon {\r\n    color: t(colorTextSuccessInverse);\r\n    fill: t(colorTextSuccessInverse);\r\n}\r\n\r\n.THIS.slds-scope .strike-icon-text-disabled {\r\n    color: t(colorTextIconDefaultDisabled);\r\n    fill: t(colorTextIconDefaultDisabled);\r\n}\r\n\r\n.THIS.slds-scope .strike-icon-text-disabled .slds-icon {\r\n    color: t(colorTextIconDefaultDisabled);\r\n    fill: t(colorTextIconDefaultDisabled);\r\n}\r\n\r\n.THIS.slds-scope .strike-button {\r\n    white-space: nowrap;\r\n}\r\n\r\n.THIS.slds-scope .strike-button_large {\r\n    padding-left: 2rem;\r\n    padding-right: 2rem;\r\n    font-size: 1rem;\r\n    line-height: 2.5rem;\r\n}\r\n\r\n.THIS .strike-progress-ring_completed-container .slds-progress-ring_complete {\r\n    animation: strike-section-completion 250ms ease 250ms both;\r\n}\r\n\r\n.THIS.slds-scope .strike-help {\r\n    padding: 0;\r\n    overflow: hidden;\r\n}\r\n\r\n.THIS.slds-scope .strike-help__header {\r\n    padding: t(spacingLarge);\r\n}\r\n\r\n.THIS.slds-scope .strike-help__header a,\r\n.THIS.slds-scope .strike-help__header a:hover,\r\n.THIS.slds-scope .strike-help__header a:active,\r\n.THIS.slds-scope .strike-help__header a:focus {\r\n    color: #fff;\r\n    text-decoration: underline;\r\n}\r\n\r\n.THIS.slds-scope .strike-help__header \u003e .slds-grid {\r\n    -webkit-flex-wrap: wrap;\r\n    -ms-flex-wrap: wrap;\r\n    flex-wrap: wrap;\r\n}\r\n\r\n@media (min-width: 48em) {\r\n    .THIS.slds-scope .strike-help__header \u003e .slds-grid {\r\n        -webkit-flex-wrap: nowrap;\r\n        -ms-flex-wrap: nowrap;\r\n        flex-wrap: nowrap;\r\n    }\r\n}\r\n\r\n.THIS.slds-scope .strike-help__header .slds-list_horizontal.slds-has-dividers \u003e .slds-list__item:after {\r\n    background-color: white;\r\n}\r\n\r\n.THIS.slds-scope .strike-help__contact-info {\r\n    text-align: left;\r\n    -webkit-box-pack: start;\r\n    -webkit-justify-content: flex-start;\r\n    -ms-flex-pack: start;\r\n    justify-content: flex-start;\r\n}\r\n\r\n@media (min-width: 48em) {\r\n    .THIS.slds-scope .strike-help__contact-info {\r\n        -webkit-box-pack: end;\r\n        -webkit-justify-content: flex-end;\r\n        -ms-flex-pack: end;\r\n        justify-content: flex-end;\r\n    }\r\n}\r\n\r\n.THIS.slds-scope .strike-help__contact-info a {\r\n    text-decoration: none;\r\n    color: #fff;\r\n}\r\n\r\n.THIS.slds-scope .strike-help__body {\r\n    padding: t(spacingLarge);\r\n}\r\n\r\n.THIS.slds-scope .strike-help__links-header {\r\n    margin-top: t(spacingMedium);\r\n}\r\n\r\n@media (min-width: 48em) {\r\n    .THIS.slds-scope .strike-help__links-header {\r\n        margin-top: 0;\r\n    }\r\n}\r\n\r\n.THIS.slds-scope .strike-help__columns {\r\n    -webkit-column-count: 2;\r\n    -moz-column-count: 2;\r\n    column-count: 2;\r\n    -webkit-column-gap: 2rem;\r\n    -moz-column-gap: 2rem;\r\n    column-gap: 2rem;\r\n}\r\n\r\n.THIS.slds-scope .strike-progress {\r\n    pointer-events: none;\r\n}\r\n\r\n.THIS.slds-scope .strike-progress .slds-progress__list {\r\n    height: 22px;\r\n}\r\n\r\n.THIS.slds-scope .strike-progress li .slds-progress__marker_icon {\r\n    width: 0.875rem;\r\n    height: 0.875rem;\r\n    box-sizing: content-box;\r\n}\r\n\r\n.THIS.slds-scope .strike-progress li .slds-progress__marker_icon .slds-button__icon {\r\n    width: 0.875rem;\r\n    height: 0.875rem;\r\n}\r\n\r\n.THIS .strike-setup-toast {\r\n    transition: all 250ms ease 0ms;\r\n    opacity: 0;\r\n    pointer-events: none;\r\n}\r\n\r\n.THIS .strike-setup-toast.show {\r\n    opacity: 1;\r\n    pointer-events: auto;\r\n}\r\n\r\n.THIS.slds-scope .slds-button-group .slds-dropdown-trigger:last-child .slds-button {\r\n    border-radius: 0 0.25rem 0.25rem 0;\r\n    margin-left: 0;\r\n}\r\n\r\n.THIS .strike-progress-bar slds-progress-bar__value,\r\n.THIS .slds-progress-ring_complete {\r\n    background-color: t(colorBackgroundSuccess);\r\n}\r\n\r\n.THIS .slds-path__link:hover,\r\n.THIS .slds-path__link:active,\r\n.THIS .slds-path__link:focus,\r\n.THIS .slds-path__item,\r\n.THIS .slds-path__item::before {\r\n    text-decoration: none;\r\n    cursor: default;\r\n}\r\n"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
	at com.salesforce.slds.lsp.diagnostics.Diagnoser.diagnose(Diagnoser.java:75)
	at com.salesforce.slds.lsp.services.TextDocumentServiceImpl.diagnose(TextDocumentServiceImpl.java:142)
	at com.salesforce.slds.lsp.services.TextDocumentServiceImpl.didOpen(TextDocumentServiceImpl.java:61)
	... 16 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.salesforce.slds.lsp.diagnostics.Diagnoser.diagnose(Diagnoser.java:71)
	... 18 more

Jun 01, 2021 9:28:34 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification

**Comment by billyma** [comment]
Let me take a look, and post an update later.

**Comment by billyma** [comment]
@gogowater - I was able to reproduce your issue, and identified a fix for it. I will update this thread once the fix is released.

**Comment by billyma** [comment]
@gogowater - Fix is released. Please update the extension to get the change.
